### ISSUE TITLE
08 Stateful Services failed - unable to load Thin

### ISSUE THREAD

**Issue by garnerp** [EngineerBetter/training-zero-to-hero#4]
[OUT] bundler: failed to load command: thin (/home/vcap/app/vendor/bundle/ruby/2.2.0/bin/thin)

Sorry I'm not a Ruby guy.  I had to bump the Gemfile ruby version to a supported version of PWS (went to 2.2.5 and 2.3.3), but same error on cf push.

**Comment by MohammedFadin** [comment]
My customer reported the same issue as well. I don't see any fix since last year.
